

export const Images = {
    splashScreensLogo: require('./splashScreensLogo.png'),
    ethRoundWithStars: require('./ethRoundWithStars.png'),
    slider1: require('./slider1.png'),
    radioUnFill: require('./radioUnFill.png'),
    questionMark: require('./questionMark.png'),
    goBackArrow: require('./goBackArrow.png'),
    walletLogo: require('./walletLogo.png'),
    seamLessSetup: require('./seamLessSetup.png'),
    seamLessSetup: require('./seamLessSetup.png'),
    greenLock: require('./greenLock.png'),
    heart: require('./heart.png'),
    apple: require('./apple.png'),
    google: require('./google.png'),
    slider2: require('./slider2.png'),
    purpleLock: require('./purpleLock.png'),
    face: require('./face.png'),
    toggleOn: require('./toggleOn.png'),
    toggleOff: require('./toggleOff.png'),
    congratulations: require('./congratulations.png'),
    enjoyYourWallet: require('./enjoyYourWallet.png'),
    plusWithBox: require('./plusWithBox.png'),
    key: require('./key.png'),
    slideLine1: require('./slideLine1.png'),
    slideLine2: require('./slideLine2.png'),
    bgImage: require('./bgImage.png'),
    importAccountCircle: require('./importAccountCircle.png'),
    tickGreenCircle: require('./tickGreenCircle.png'),
    checkBox: require('./checkBox.png'),
    unCheckBox: require('./unCheckBox.png'),
    tokenLogo: require('./tokenLogo.png'),
    arrowDownWithRound: require('./arrowDownWithRound.png'),
    arrowRight: require('./arrowRight.png'),
    pasteImage: require('./pasteImage.png'),
    ethereum: require('./ethereum.png'),
    base: require('./base.png'),
    sui: require('./sui.png'),
    polygon: require('./polygon.png'),
    bitcoin: require('./bitcoin.png'),
}